window:
  decorations: buttonless
  opacity: 0.99
  padding:
    x: 2
    y: 2

colors:
  # Default colors
  primary:
    background: '0x262626'
    foreground: '0x959dcb'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x292d3e'
    cursor: '0xffcc00'

  # Normal colors
  normal:
    black:   '0x292d3e'
    red:     '0xf07178'
    green:   '0xc3e88d'
    yellow:  '0xffcb6b'
    blue:    '0x82aaff'
    magenta: '0xc792ea'
    cyan:    '0x89ddff'
    white:   '0xd0d0d0'

  # Bright colors
  bright:
    black:   '0x434758'
    red:     '0xff8b92'
    green:   '0xddffa7'
    yellow:  '0xffe585'
    blue:    '0x9cc4ff'
    magenta: '0xe1acff'
    cyan:    '0xa3f7ff'
    white:   '0xfefefe'

# Font configuration
font:
  normal:
    family: "SauceCodePro Nerd Font"
    style: Regular
  bold:
    family: "SauceCodePro Nerd Font"
    style: Bold
  italic:
    family: "SauceCodePro Nerd Font"
    style: Italic
  bold_italic:
    family: "SauceCodePro Nerd Font"
    style: Bold Italic

  # Point size
  size: 13.0

draw_bold_text_with_bright_colors: true

alt_send_esc: true

# https://github.com/alacritty/alacritty/issues/2017#issuecomment-581707489
# More key bindings
key_bindings:
  - { key: Period, mods: Alt,             chars: "\x1B." }
  - { key: Left,   mods: Alt,             chars: "\x1Bb" }
  - { key: Right,  mods: Alt,             chars: "\x1Bf" }
  - { key: Key0,   mods: Command,         action: ResetFontSize    }
  - { key: Equals, mods: Command,         action: IncreaseFontSize }
  - { key: Plus,   mods: Command,         action: IncreaseFontSize }
  - { key: Minus,  mods: Command,         action: DecreaseFontSize }
  - { key: H,      mods: Command,         action: Hide             }
  - { key: M,      mods: Command,         action: Minimize         }
  - { key: Q,      mods: Command,         action: Quit             }
  - { key: N,      mods: Command,         action: SpawnNewInstance }
  - { key: F,      mods: Command|Control, action: ToggleFullscreen }
